package com.example.carworth.uix.view.fonk

class Listeler(){
    val arabaMarkalari = listOf(
        "Alfa Romeo", "Audi", "BMW", "Chevrolet", "Chery", "Chrysler", "Citroen", "Cupra",
        "Dacia", "Daewoo", "Daihatsu", "DS Automobiles", "Fiat", "Ford", "Geely", "Honda",
        "Hyundai", "Ikco", "Jaguar", "Kia", "Lada", "Lancia", "Maserati", "Mazda", "Mercedes - Benz",
        "Mini", "Mitsubishi", "Nissan", "Opel", "Peugeot", "Porsche", "Renault", "Seat", "Smart", "Subaru",
        "Suzuki", "Tata", "Toyota", "Tofaş", "Volkswagen", "Volvo"
    )
    val sehirList=listOf("Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin",
        "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa",
        "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum",
        "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir",
        "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kilis", "Kırıkkale", "Kırklareli", "Kırşehir",
        "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir",
        "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şanlıurfa",
        "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak")

    val arabaModel = mapOf(
        "Alfa Romeo" to listOf("Giulietta", "156", "147", "159", "MiTo", "145"),
        "Audi" to listOf("A4", "A3", "A6", "A1", "A5", "A8", "A7", "80 Serisi", "TT"),
        "BMW" to listOf("3 Serisi", "1 Serisi", "5 Serisi", "2 Serisi", "4 Serisi", "6 Serisi", "7 Serisi"),
        "Chery" to listOf("Kimo", "Alia", "Chance", "Niche"),
        "Chevrolet" to listOf("Aveo", "Kalos", "Cruze", "Lacetti", "Spark", "Epica", "Rezzo", "Evanda"),
        "Chrysler" to listOf("Stratus", "300 M", "Sebring", "300 C"),
        "Citroen" to listOf("Saxo", "C5", "C-Elysee", "C3", "C4", "Xsara", "C4 Picasso", "C4 X", "Xantia", "C1", "e-C4 X", "C2", "C4 Grand Picasso", "C3 Picasso"),
        "Cupra" to listOf("Leon"),
        "DS Automobiles" to listOf("DS4"),
        "Dacia" to listOf("Logan", "Sandero", "Solenza", "Lodgy", "Jogger"),
        "Daewoo" to listOf("Nubira", "Leganza", "Lanos", "Tico", "Matiz"),
        "Daihatsu" to listOf("Cuore", "Sirion", "Applause", "Materia", "Move"),
        "Dodge" to listOf("Challenger"),
        "Fiat" to listOf("Egea", "Linea", "Palio", "Brava", "Albea", "Punto", "Marea", "Stilo", "500 Ailesi", "Panda", "Bravo", "Tempra", "Idea"),
        "Ford" to listOf("Focus", "Fiesta", "C-Max", "S-Max", "Fusion", "Mondeo", "Grand C-Max", "B-Max", "Galaxy", "Ka"),
        "Geely" to listOf("Familia", "Emgrand", "FC", "Echo"),
        "Honda" to listOf("Civic", "Accord", "Jazz", "City", "Legend"),
        "Hyundai" to listOf("Accent Era", "i20", "Accent", "Accent Blue", "Sonata", "i20 Troy", "i30", "Getz", "Matrix", "i10", "Elantra", "i20 Active", "Atos", "Coupe", "Ioniq", "i20 N", "ix20"),
        "Ikco" to listOf("Samand"),
        "Infiniti" to listOf("Q30"),
        "Jaguar" to listOf("X-Type", "XE", "XF", "S-Type"),
        "Kia" to listOf("Cerato", "Picanto", "Rio", "Ceed", "Shuma", "Pride", "Venga", "Sephia", "Carnival", "Pro Ceed", "Cadenza", "Carens"),
        "Lada" to listOf("Samara", "Vega", "Kalina"),
        "Lancia" to listOf("Delta", "Ypsilon", "Thema"),
        "Maserati" to listOf("Ghibli"),
        "Mazda" to listOf("3", "323", "626", "6", "2", "5"),
        "Mercedes - Benz" to listOf("E", "C", "S", "A", "CLA", "200", "B", "CLK", "CLE", "CLS", "SLK", "AMG GT", "CLC", "190"),
        "Mini" to listOf("Cooper", "Cooper S", "Cooper Clubman"),
        "Mitsubishi" to listOf("Lancer", "Carisma", "Colt", "Space Star", "Attrage"),
        "Nissan" to listOf("Micra", "Almera", "Primera", "Note", "Pulsar", "Maxima", "Laurel Altima"),
        "Opel" to listOf("Insignia", "Astra", "Corsa", "Meriva", "Vectra", "Zafira", "Tigra", "Omega"),
        "Peugeot" to listOf("207", "206", "106", "508", "107", "301", "208", "307", "308", "306", "206+", "407", "406", "RCZ", "807"),
        "Porsche" to listOf("Panamera"),
        "Proton" to listOf("418", "415", "Gen 2", "315", "Waja"),
        "Renault" to listOf("Megane", "Clio", "Symbol", "Fluence", "Talisman", "Laguna", "Modus", "Taliant", "Latitude", "Scenic", "Grand Scenic", "Safrane", "Espace", "Twingo"),
        "Rover" to listOf("214", "216", "414", "25", "75", "416"),
        "Seat" to listOf("Ibiza", "Leon", "Toledo", "Cordoba", "Alhambra", "Exeo", "Altea"),
        "Skoda" to listOf("Octavia", "Fabia", "Scala", "SuperB", "Rapid", "Felicia", "Roomster"),
        "Smart" to listOf("ForFour", "ForTwo"),
        "Subaru" to listOf("Legacy", "Impreza"),
        "Suzuki" to listOf("Swift", "Maruti", "Liana", "Alto", "Splash", "SX4"),
        "Tata" to listOf("Manza", "Indigo", "Vista", "Indica", "Marina"),
        "Tofaş" to listOf("Doğan", "Şahin", "Kartal"),
        "Toyota" to listOf("Corolla", "Yaris", "Auris", "Avensis", "Carina", "Verso", "Starlet", "Camry", "Urban Cruiser"),
        "Volkswagen" to listOf("Golf", "Polo", "Passat", "Jetta", "VW CC", "Bora", "Passat Variant", "Scirocco", "New Beetle", "Arteon", "Touran", "Sharan", "Phaeton"),
        "Volvo" to listOf("S60", "V40", "S40", "S90", "S80", "V90 Cross Country", "C30", "V40 Cross Country", "V70")
    )
    val arabaSeri = mapOf(
        "1 Serisi" to listOf("116d ED EfficientDynamics", "116i Joy Edition", "120d", "118i Joy Plus", "116i Sport Line", "116d Premium Line", "116i Standart", "118i Standart", "116i Comfort", "118i", "116i Premium", "118i Pure", "116d Joy", "116d ED Sport Line", "118i Premium Line", "118i Joy", "116i M Sport", "116d First Edition M Sport", "118i M Sport", "116d Joy Plus", "116d First Edition Sport Line", "116d Sport Line", "116d Comfort", "118i M Plus", "116d M Sport", "116d ED Joy Plus", "116d M Plus", "120i Standart", "116i Advantage", "118i Premium", "118i First Edition Sport Line", "116i Urban Line", "116d One Edition"),
        "106" to listOf("GTI", "XR", "XN", "Quicksilver", "XS"),
        "107" to listOf("1.4 HDi Trendy", "1.0 Trendy", "1.0 Urban Move"),
        "145" to listOf("1.6 TS Sportivo"),
        "147" to listOf("1.6 TS Distinctive"),
        "156" to listOf("1.6 TS Distinctive", "2.0 TS", "1.6 TS Progression", "1.6 TS", "2.0 JTS Distinctive"),
        "159" to listOf("1.9 JTD Distinctive", "1.9 JTD Distinctive Plus", "1.9 JTD Progression"),
        "190" to listOf("2.0"),
        "2" to listOf("1.5 Sport"),
        "2 Serisi" to listOf("216d Gran Coupe First Edition M Sport", "216d Gran Coupe First Edition Sport Line", "216d Gran Coupe Sport Line", "218i Active Tourer Active Tourer", "218i Gran Coupe First Edition Sport Line", "216d Active Tourer Active Tourer", "230e xDrive M Sport", "216d Gran Coupe First Edition Luxury Line", "216d Gran Tourer Luxury Line", "216d Active Tourer Sport Line"),
        "200" to listOf("E"),
        "206" to listOf("1.6 CC", "2.0 GTI", "1.4 Comfort", "1.4 XT", "1.4 Fever", "1.6 XT", "1.4 Desire", "1.4 XR", "1.4 HDi X-line", "1.4 Color Line", "1.4 X-Line", "1.4 HDi X-Design", "1.6 Sport", "1.4 Executive", "1.4 HDi Desire", "1.4 X-Design", "1.4 HDi Panoramic", "1.4 HDi Comfort", "1.4 Generation", "1.4 HDi Sporty", "1.4 Feline", "1.4 Look", "1.4 HDi Fever", "1.6 Roland Garros", "1.6 Quicksilver", "1.4 HDi Feline", "1.6 XSi", "1.4 Sport", "1.6 XS", "1.4 HDi Look", "1.4 Premium", "1.4 XS"),
        "206+" to listOf("1.4 Comfort", "1.4 HDi Comfort", "1.4 HDi Envy", "1.4 Envy", "1.4 HDi Urban Move", "1.4 Urban Move", "1.4 HDi Sportium"),
        "207" to listOf("1.4 Trendy", "1.4 HDi Trendy", "1.4 HDi Premium", "1.4 Envy", "1.4 HDi Urban Move", "1.4 HDi Active", "1.6 HDi Premium", "1.4 HDi Allure", "1.4 HDi Millesim", "1.4 Comfort", "1.6 VTi Premium", "1.4 VTi Trendy", "1.6 HDi Outdoor", "1.6 VTi Sportium", "1.4 HDi Envy", "1.6 VTi Active", "1.4 HDi Sportium", "1.6 HDi Dynamic", "1.4 VTi Premium", "1.4 VTi Active", "1.4 VTi Limited", "1.6 HDi Dynamic CC", "1.6 HDi Trendy", "1.6 HDi Active"),
        "208" to listOf("1.4 HDi Access", "1.4 HDi Active", "1.2 PureTech Allure", "1.2 PureTech Access", "1.2 PureTech Active", "1.2 PureTech GT Line", "1.2 PureTech Allure Selection", "1.2 PureTech Active Prime", "1.6 VTi Allure", "1.5 BlueHDi Signature Dynamic", "1.5 BlueHDi Signature", "1.6 THP Allure", "1.6 HDi Allure", "1.2 VTi Access", "1.2 PureTech Prime", "1.5 BlueHDi Active", "1.0 VTi Access", "1.6 BlueHDi Active", "1.5 BlueHDi Active Dynamic", "1.2 VTi Active", "1.6 HDi Active", "1.2 PureTech Prime Selection", "1.5 BlueHDi Allure"),
        "214" to listOf("Si"),
        "216" to listOf("Si"),
        "25" to listOf("1.6 Club", "1.6 Classic"),
        "3" to listOf("1.6 Impressive", "1.5 SkyActive-D Motion", "1.6 Dynamic", "1.5 SkyActive-G Reflex", "1.6 Comfort", "1.6 Touring", "1.5 SkyActive-G Power Sense", "1.5 SkyActive-G Power", "1.6 Base", "1.5 SkyActive-G Motion", "1.6 Sport Dynamic"),
        "3 Serisi" to listOf("320i ED M Plus", "320d Techno Plus", "316i Modern Line", "318i Standart", "316i Technology", "320i Cabrio", "320d Technology", "320i ED Luxury Line", "320d M Sport", "320i", "320d Premium", "316i Standart", "320d Sport Line", "320i M Sport", "316i Sport Line", "318i Sport Plus", "320d Standart", "318d M Plus", "320i ED Modern Line Plus", "320i ED 40th Year Edition", "316i Comfort", "320i ED Sport Line", "320d Modern Line", "316i Luxury Line", "316i M Sport", "320i ED Standart", "318i Edition M Sport", "320i First Edition M Sport", "320d Edition M Sport", "320i Sport Line", "320i 50th Year M Edition", "320i ED Modern Line", "320i Premium", "330i Standart", "318i Edition Sport Line", "320d Sport", "316i Compact", "320i ED Luxury Line Plus", "320d xDrive Standart", "320d Comfort", "316i Premium", "316ti Compact", "318i Joy", "320i ED Techno Plus", "320d xDrive Techno Plus", "320d Touring", "320xd Standart", "318i Premium Line", "316Ci", "320d xDrive Prestige", "320d Luxury", "320i First Edition Sport Line", "320d Edition Comfort", "316i Advantage", "320d xDrive M Sport", "320i First Edition Luxury Line", "318Ci", "320d Premium Line", "316i Exclusive", "316i Sport", "330d M Sport", "325i Standart", "320d xDrive Premium", "318d Premium", "320d xDrive Sport Line", "318ti Compact", "320d xDrive Edition M Sport"),
        "300 C" to listOf("3.0 CRD", "2.7"),
        "300 M" to listOf("3.5"),
        "301" to listOf("1.6 HDi Active", "1.6 HDi Allure", "1.6 HDi Access", "1.2 VTi Access", "1.2 VTi Active", "1.5 BlueHDI Active", "1.5 BlueHDI Allure", "1.2 PureTech Active", "1.6 BlueHDI Active", "1.6 BlueHDI Allure", "1.2 PureTech Access", "1.6 VTi Allure", "1.6 VTi Active"),
        "306" to listOf("2.0 XRDT", "1.6 Griffe", "1.6 Platinum", "1.4 XR", "1.6 XR", "1.8 XR", "1.6 XN"),
        "307" to listOf("1.6 HDi Premium", "1.6 HDi XT", "1.6 XT", "1.6 Premium", "1.6 XR", "1.4 Comfort", "1.4 HDi XR", "1.6 HDi Comfort", "1.6 Pack", "1.6 HDi Look", "1.6 Comfort", "1.4 HDi Envy", "1.6 Look", "1.6 XS", "1.4 Look", "2.0 HDi XT", "1.6 HDi XS", "1.6 Envy", "1.6 HDi Designtech", "1.6 Profil", "2.0 HDi Premium", "1.6 Technoplus", "1.4 XR", "1.6 Designtech", "1.6 HDi Pack", "2.0 CC Sport"),
        "308" to listOf("1.6 HDi Comfort", "1.6 VTi Comfort Pack", "1.2 PureTech GT", "1.6 HDi Comfort Pack", "1.2 VTi Allure", "1.2 PureTech Style", "1.2 PureTech Allure", "1.6 VTi Comfort", "1.6 e-HDi Active", "1.6 HDi Premium Pack", "1.2 PureTech Allure Sport", "1.6 VTi Premium Plus", "1.6 VTi Access", "1.2 VTi Active", "1.6 HDi Active", "1.2 PureTech Style Tech", "1.6 HDi Millesim", "1.6 BlueHdi Style", "1.5 BlueHDI Style Tech", "1.6 VTi Millesim", "1.5 BlueHDI Style", "1.6 e-HDi Allure", "1.6 BlueHdi Allure", "1.6 BlueHdi Active", "1.6 e-HDi Access", "1.2 PureTech Active Prime", "1.6 HDi Premium", "1.6 HDi Access", "1.6 e-HDi Classic Edition Plus", "1.6 e-HDi Classic Edition", "1.6 HDi Sportium", "1.6 HDi Premium Plus", "1.6 e-HDi Sportium"),
        "315" to listOf("GLS"),
        "323" to listOf("1.6", "1.5 GLX", "1.5", "1.6 GLX"),
        "4 Serisi" to listOf("420d Gran Coupe M Sport", "420d xDrive Gran Coupe Luxury Line", "418i Gran Coupe M Sport", "420d M Sport", "418i Gran Coupe Prestige", "418i Gran Coupe Gran Coupe", "420i Gran Coupe M Sport", "418i M Sport", "420d xDrive M Sport", "420d Luxury Line", "420d xDrive Gran Coupe Sport Line", "420d Gran Coupe Gran Coupe"),
        "406" to listOf("2.0 HDi ST", "2.0 SV", "2.0 ST", "2.0 HDi SV", "1.8 SL", "1.8 ST"),
        "407" to listOf("1.6 HDi Comfort", "1.6 HDi Executive", "2.0 HDi Executive Premium", "1.6 HDi Executive Black", "2.0 HDi Executive", "2.0 HDi GT Line", "2.0 HDi Comfort", "2.0 Executive Premium", "1.6 HDi Millesim", "1.6 HDi Premium"),
        "414" to listOf("Si"),
        "415" to listOf("GLS"),
        "416" to listOf("Si"),
        "418" to listOf("GLX"),
        "5" to listOf("1.6 Sport"),
        "5 Serisi" to listOf("520d Premium", "520i Prestige", "520d Sport", "520i M Sport", "520d M Sport", "520i Premium", "520d Executive M Sport", "520i Standart", "525d xDrive Premium", "520i Luxury Line", "525d xDrive Executive Plus", "520d Comfort", "520i Comfort", "525d xDrive M Sport", "520i Executive", "530d Standart", "520d Dynamic", "520d Exclusive", "530xd Gran Turismo Premium", "520d Gran Turismo Luxury Line", "530i Standart", "525d xDrive Executive M Sport", "520d xDrive M Sport", "520d Standart", "520i Executive M Sport", "530i Executive M", "520d xDrive Executive M", "520i Executive Plus", "520d Sport Line", "520d xDrive Sport Line", "525d xDrive xDrive", "520i Business", "525d xDrive Executive", "525d xDrive Exclusive", "525d Standart", "520d xDrive Luxury Line", "520i Touring", "525tds Standart", "530d M Sport", "528i Standart", "525d xDrive Comfort", "520d Gran Turismo M Sport", "523i Standart", "520d xDrive Prestige", "530xd Gran Turismo Gran Turismo", "545i Standart", "535d xDrive Premium", "535d xDrive M Sport"),
        "500 Ailesi" to listOf("500L 1.3 Mjet Panoramic Edition", "500L 1.3 Mjet Lounge", "500L 1.4 PopStar", "500L 1.6 Mjet Lounge", "500 1.2 Lounge", "500 1.2 Collozione Winter", "500 1.3 Mjet Lounge", "500L 1.3 Mjet RockStar", "500L 1.6 Mjet Beats Edition", "500L 1.3 Mjet PopStar", "500L 1.4 T-Jet Beats Edition", "500L 1.3 Mjet Pop"),
        "508" to listOf("1.6 e-HDi Active", "1.6 THP Access", "1.6 e-HDi Allure", "1.6 e-HDi Access", "1.5 BlueHDI GT Selection", "1.5 BlueHDI Prime", "1.6 BlueHDi Access", "1.5 BlueHDI Allure", "1.6 THP Active", "1.6 BlueHDi Allure", "1.5 BlueHDI GT Line", "1.5 BlueHDI GT", "1.6 BlueHDi Active", "1.6 HDi Allure", "1.6 VTi Access", "1.6 HDi Active", "2.0 HDi Active", "1.6 Puretech Allure", "1.6 THP Allure", "2.0 HDi Allure", "1.6 HDi Access", "1.6 Puretech Prime"),
        "6" to listOf("2.0 Sport", "2.0 Dynamic", "2.0 TE", "2.0 CDH TE"),
        "6 Serisi" to listOf("635d Cabrio"),
        "626" to listOf("2.0", "2.0 GLX"),
        "7 Serisi" to listOf("730d Standart", "740d xDrive Long Pure Excellence", "745i", "740d xDrive Long M Excellence", "730d Long Standart", "725d Long M Sport", "730d Long Exclusive", "730d xDrive Long Executive Lounge", "730d Long Individual Edition", "740d xDrive M Sport", "735i Long", "735i"),
        "75" to listOf("2.0 Club", "2.0 Classic"),
        "80 Serisi" to listOf("1.9 TDI"),
        "807" to listOf("2.2 HDi Executive"),
        "A" to listOf("A 180 CDI BlueEFFICIENCY Style", "A 180 CDI BlueEFFICIENCY AMG", "A 180 d Style", "A 200 AMG", "A 180 BlueEFFICIENCY AMG Sport", "A 180 d AMG", "A 180 CDI BlueEFFICIENCY Prime", "A 160 Elegance", "A 150 Avantgarde", "A 180 BlueEFFICIENCY Urban", "A 180 CDI BlueEFFICIENCY AMG Sport", "A 200 BlueEFFICIENCY AMG Sport", "A 150 Polarstar", "A 160 Avantgarde", "A 200 Progressive", "A 190 Elegance", "A 180 d AMG Orange Art", "A 160 Classic", "A 150 Elegance", "A 180 CDI BlueEFFICIENCY Urban"),
        "A1" to listOf("1.6 TDI Sportback Ambition", "1.6 TDI Sportback Attraction"),
        "A3" to listOf("A3 Sedan 1.6 TDI Ambiente", "A3 Sportback 1.6 TDI Ambition", "A3 Sedan 1.6 TDI Attraction", "A3 Sportback 1.6 Ambiente", "A3 Sedan 1.6 TDI Sport Line", "A3 Sportback 1.6 Ambition", "A3 Sedan 1.6 TDI S Line", "A3 Sportback 1.6 Attraction", "A3 Sedan 35 TFSI Advanced", "A3 Sedan 1.6 TDI Design Line", "A3 Sedan 30 TDI Design", "A3 Sedan 35 TFSI Dynamic", "A3 Sportback 1.6 TDI Attraction", "A3 Sedan 1.6 TDI Dynamic", "A3 Sportback 30 TFSI Dynamic", "A3 Sportback 1.2 TFSI Attraction", "A3 Sportback 1.6 TDI Ambiente", "A3 Sportback 1.6 TDI Design Line", "A3 Sportback 1.4 TFSI Attraction", "A3 Sedan 35 TFSI S-Line", "A3 Sportback 1.0 TFSI Dynamic", "A3 Sportback 30 TDI Design", "A3 Sedan 1.4 TFSI Attraction", "A3 Sedan 1.6 TDI Ambition", "A3 Sportback 1.6 TDI Sport Line", "A3 Sportback 35 TFSI Sport", "A3 Sportback 1.4 TFSI Ambition", "A3 Sportback 1.6 FSI", "A3 Sportback 35 TFSI Advanced", "A3 Sportback 35 TFSI Dynamic", "A3 Sedan 30 TFSI Dynamic", "A3 Sportback 1.6 Sportback Attraction", "A3 Sportback 1.6 Sportback Ambiente", "A3 Sportback 2.0 FSI Attraction", "A3 Sportback 1.6 Standart", "A3 Sportback 35 TFSI S-Line", "A3 Sedan 35 TFSI Sport", "A3 Sportback 1.6 Sportback Standart", "A3 Sportback 1.4 TFSI", "A3 Sportback 1.0 TFSI Sport Line", "A3 Sportback 1.6 Sportback Ambition"),
        "A4" to listOf("A4 Sedan 2.0 TDI Quattro", "A4 Sedan 2.0 TDI", "A4 Sedan 40 TDI Quattro Advanced", "A4 Sedan 1.4 TFSI Dynamic", "A4 Sedan 1.6", "A4 Sedan 40 TDI Advanced", "A4 Sedan 1.4 TFSI Design", "A4 Sedan 1.8 T Quattro", "A4 Sedan 2.0 TDI Quattro Dynamic", "A4 Sedan 1.4 TFSI Sport", "A4 Sedan 2.0 TFSI Quattro", "A4 Sedan 1.8", "A4 Sedan 1.8 TFSI", "A4 Avant 2.0 TDI", "A4 Avant 2.0 TFSI Quattro", "A4 Allroad Quattro 2.0 TDI", "A4 Sedan 1.9 TDI", "A4 Sedan 2.0 TDI Quattro Design", "A4 Sedan 2.0 TDI Dynamic", "A4 Sedan 1.8 T", "A4 Sedan 2.0 TDI Sport", "A4 Avant 2.7"),
        "A5" to listOf("A5 Sportback 2.0 TDI", "A5 Sportback 1.4 TFSI", "A5 Sportback 2.0 TDI Quattro", "A5 Sportback 45 TFSI Quattro S Line", "A5 Coupe 1.8 TFSI", "A5 Coupe 2.0 TFSI Quattro"),
        "A6" to listOf("A6 Sedan 40 TDI Quattro Sport", "A6 Sedan 3.0 TDI Quattro", "A6 Sedan 40 TDI Quattro Design", "A6 Sedan 2.0 TDI", "A6 Sedan 2.0 TDI Quattro", "A6 Sedan 2.0 TFSI", "A6 Sedan 2.8 Quattro", "A6 Sedan 2.0 TFSI Quattro", "A6 Avant 2.7 TDI", "A6 Sedan 2.4", "A6 Sedan 3.0", "A6 Avant 2.0 TDI Quattro", "A6 Sedan 1.8 T Advance", "A6 Avant 2.0", "A6 Avant 2.0 TDI", "A6 Sedan 45 TFSI Quattro Sport", "A6 Sedan 3.0 Quattro", "A6 Sedan 50 TDI Quattro Design", "A6 Sedan 2.7 T Quattro", "A6 Avant 3.0 TDI Quattro", "A6 Sedan 2.0", "A6 Sedan 1.8 T Quattro"),
        "A7" to listOf("40 TDI", "2.0 TFSI"),
        "A8" to listOf("2.5 TDI", "3.0 TDI Quattro Long", "50 TDI Quattro Long", "3.0 TDI Quattro"),
        "AMG GT" to listOf("63 4Matic"),
        "Accent" to listOf("1.5 GLS", "1.5 CRDi Admire", "1.5 GT", "1.3 LS", "1.6 Admire", "1.3 LX", "1.3 Admire", "1.5 1.5i GL", "1.5 1.5i GLS", "1.5 CRDi GLS", "1.3 GLS", "1.5 GL", "1.3 1.3i", "1.3 LX Allegro", "1.5 CRDi Comfort", "1.3 GT", "1.5 LX", "1.3 GLS Active", "1.5 CRDi LS"),
        "Accent Blue" to listOf("1.6 CRDI Biz", "1.6 CRDI Mode Plus", "1.4 D-CVVT Mode Plus", "1.4 CVVT Mode Plus", "1.6 CRDI Prime", "1.6 CRDI Mode", "1.4 CVVT Mode", "1.4 D-CVVT Mode", "1.4 D-CVVT Prime", "1.4 CVVT Prime", "1.4 CVVT Biz"),
        "Accent Era" to listOf("1.4 Team", "1.4 Start", "1.4 Mode", "1.5 CRDi-VGT Team", "1.6 Select", "1.4 Select", "1.6 Team", "1.5 CRDi Mode", "1.5 CRDi-VGT Select", "1.5 CRDi-VGT Style", "1.5 CRDi-VGT Start", "1.5 CRDi Style", "1.5 CRDi Select", "1.5 CRDi Team", "1.6 Expo Platinum", "1.5 CRDi Start", "1.4 Select Expo Gold", "1.4 Prime", "1.5 CRDi Prime", "1.6 Style", "1.4 Expo Gold", "1.4 Eco", "1.5 CRDi-VGT Eco"),
        "Accord" to listOf("2.4 Executive", "1.8 LS", "2.0 Executive", "2.0 Sport", "1.5 VTEC Executive", "3.0", "2.2 CTDi", "1.5 VTEC Executive Plus", "2.0 ES"),
        "Albea" to listOf("Sole 1.3 Multijet Active", "1.3 Multijet Active", "Sole 1.4 Fire Dynamic", "1.2 Dynamic", "1.4 Fire Active", "Sole 1.3 Multijet Dynamic", "1.2 Active", "1.3 Multijet EL", "1.2 EL", "1.6 HL", "Sole 1.4 Fire Premio", "Sole 1.4 Fire Active", "1.3 Multijet SL", "1.2 SL", "Sole 1.3 Multijet Active Plus", "Sole 1.3 Multijet Premio Plus", "Sole 1.4 Fire Premio Plus", "1.4 Fire Dynamic", "Sole 1.3 Multijet Premio", "1.3 Multijet Dynamic", "Sole 1.4 Fire Active Plus", "1.6 Dynamic", "1.2 HL", "Sole 1.3 Multijet Dynamic Plus", "Sole 1.4 Fire Dynamic Plus"),
        "Alhambra" to listOf("1.9 TDI"),
        "Alia" to listOf("1.6 Acteco Lusso", "1.6 Acteco Norma"),
        "Almera" to listOf("1.5 Comfort", "1.5 Tekna", "1.5 Luxury", "1.5 Visia", "1.6 SLX"),
        "Altea" to listOf("1.4 TSI Style XL", "1.6 TDI Style XL", "1.9 TDI Style", "1.6 Stylance"),
        "Alto" to listOf("1.0 GL", "1.1 GLX", "1.0"),
        "Applause" to listOf("1.6 Li"),
        "Arteon" to listOf("2.0 TDI R Line"),
        "Astra" to listOf("1.6 Edition Plus", "1.3 CDTI Sport", "1.6 Edition", "1.4 T Enjoy Plus", "1.4 T Enjoy Active", "1.6 Enjoy", "1.6 Essentia", "1.6 CDTI Dynamic", "1.4 T Sport", "1.4 Club", "1.6 Sport", "1.6 CDTI Elite", "1.4 Classic", "1.6 CD", "1.6 GL", "1.6 Enjoy Plus", "1.3 CDTI Enjoy Plus", "1.3 CDTI Enjoy", "1.6 Essentia Konfor", "1.4 T Cosmo", "1.6 Enjoy Elegance", "1.4 T Edition Plus", "1.3 CDTI Essentia", "1.2 T GS", "1.6 Elegance", "1.6 CDTI Enjoy", "1.6 Classic", "1.6 CDTI Sport", "1.3 CDTI Essentia Konfor", "1.3 CDTI Enjoy Elegance", "1.4 GL", "1.6 CDTI Design", "1.3 CDTI Edition", "1.6 CDTI Edition", "1.6 Enjoy 111.Yıl", "1.6 Comfort", "1.3 CDTI Cosmo", "1.6 Business", "1.6 Classic Twinport", "1.6", "1.4 T Sport Still", "1.6 Cosmo", "1.3 CDTI ecoFLEX Sport", "1.6 CDTI Edition Plus", "1.8 CD", "1.4 Comfort", "1.3 CDTI Enjoy 111.Yıl", "1.6 CDTI Cosmo", "1.4 Essentia", "1.4 T Enjoy", "1.4 T Dynamic", "1.6 CDTI Business", "1.2 T Edition", "1.4 Enjoy", "1.6 CDX", "1.5 D Edition", "2.0 Sport", "1.3 CDTI ecoFLEX Cosmo", "1.6 CDTI Excellence", "1.4 Enjoy Plus", "1.4 T GS Line", "1.5 D GS Line", "1.3 CDTI ecoFLEX Enjoy Plus", "1.4 Start", "1.3 CDTI Business", "1.0 T Enjoy", "2.0 DTI", "1.8 Sport", "1.3 CDTI Elegance", "1.7 DTI", "1.6 GTC Sport", "1.4 T GTC Sport", "2.0 T Sport", "1.6 Cabrio", "1.6 Coupe", "1.6 T Cosmo", "1.3 CDTI Edition Plus", "1.6 100.Yıl", "1.6 Club", "1.6 CDTI Dynamic Elite", "1.3 CDTI Enjoy Active", "1.8 Coupe", "1.3 CDTI ecoFLEX Enjoy", "1.3 CDTI Active", "1.4 T Elegance", "1.4 T Business", "1.6 T Sport"),
        "Atos" to listOf("1.1 GLS", "1.0 GLS"),
        "Attrage" to listOf("1.2 Intense"),
        "Auris" to listOf("1.33 Life", "1.33 Comfort", "1.4 D-4D Blue", "1.4 D-4D Comfort", "1.6 Sport", "1.4 D-4D Elegant", "1.4 D-4D Comfort Extra", "1.4 D-4D Advance", "1.4 D-4D Advance Skypack", "1.6 Elegant", "1.4 D-4D Active Skypack", "1.4 D-4D Comfort Plus", "1.6 Touring Sports Advance Skypack", "1.6 Comfort Extra", "1.6 Active", "1.6 Active Skypack", "1.6 Advance", "1.4 D-4D Active", "1.6 Premium", "1.6 Comfort", "1.6 Advance Skypack", "1.4 D-4D Life", "1.6 Touch", "1.4 D-4D Class", "1.4 D-4D Premium"),
        "Avensis" to listOf("1.6 Elegant Extra", "1.6 Elegant", "2.0 Sol", "2.0 Liftback", "2.0 Premium", "1.6 Comfort", "2.0 Elegant", "2.0 Executive Elegant", "1.8 Elegant Extra", "2.0 Sol Extra", "1.8 Elegant", "1.6 D-4D Premium", "2.0 D-4D Elegant", "2.0 Comfort", "1.6 D-4D Premium Plus", "1.6 Linea", "2.0 Base", "1.8 Terra", "2.0 D-4D Premium"),
        "Aveo" to listOf("1.4 S", "1.4 SE", "1.2 SE", "1.2 LS", "1.2 S", "1.4 LS", "1.3 D LTZ", "1.3 D LS", "1.4 LT", "1.4 SX", "1.3 D LT", "1.4 LTZ"),
        "B" to listOf("B 180 CDI BlueEFFICIENCY Elite", "B 180 CDI BlueEFFICIENCY Urban", "B 200 CDI Special Edition", "B 180 Progressive", "B 180 BlueEFFICIENCY Elite", "B 150 Prestige", "B 180 CDI Special Edition", "B 150 150", "B 160 Boyut", "B 160 Sport", "B 150 Boyut", "B 180 CDI 180 CDI", "B 150 Special Edition"),
        "B-Max" to listOf("1.6 Titanium", "1.5 TDCi Titanium", "1.0 GTDi Titanium", "1.6 TDCi Trend", "1.6 TDCi Titanium", "1.6 Trend"),
        "Bora" to listOf("1.6 Comfortline", "1.6 Pacific", "1.9 TDi Pacific", "1.6 Basic", "1.6 Primeline", "1.9 TDi Comfortline", "1.6 Trendline", "1.6 Highline", "1.6 Comfortline Variant"),
        "Brava" to listOf("1.6 SX", "1.6 ELX"),
        "Bravo" to listOf("1.6 SX", "1.6 Mjet Emotion", "1.6 Mjet Dynamic", "1.4 Active Plus", "1.6 Mjet Dynamic Plus", "1.6 Mjet Active Plus", "1.6 Mjet Sports Style", "1.4 T-Jet Sports Style", "1.4 Active", "1.4 T-Jet Dynamic"),
        "C" to listOf("C 180 BlueEFFICIENCY Avantgarde", "C 200 D Comfort", "C 200 D Exclusive", "C 200 AMG", "C 200 d BlueTEC AMG", "C 180 Kompressor BlueEFFICIENCY AMG", "C 200 D AMG", "C 200 d BlueTEC Fascination", "C 200 d BlueTEC Exclusive", "C 180 BlueEFFICIENCY AMG", "C 180 Kompressor BlueEfficiency Avantgarde", "C 180 AMG", "C 180 BlueEFFICIENCY Fascination", "C 220 CDI AMG", "C 200 Kompressor Avantgarde", "C 200 Elegance", "C 180 Kompressor Sport Edition", "C 180 Avantgarde", "C 220 CDI Elegance", "C 180 Fascination", "C 180 BlueEFFICIENCY Selection Plus", "C 180 BlueEFFICIENCY Prime", "C 180 Kompressor BlueEfficiency Fascination", "C 200 All-Terrain", "C 200 d BlueTEC Avantgarde", "C 220 CDI Avantgarde", "C 200 d BlueTEC Style", "C 180 BlueEfficiency Start", "C 200 d BlueTEC Comfort", "C 200 Kompressor Classic", "C 200 BlueTEC AMG", "C 180 Kompressor BlueEfficiency Luxury", "C 250 TD Elegance", "C 200 Avantgarde", "C 200 D Avantgarde", "C 200 Kompressor Elegance", "C 180 Elegance", "C 180 Kompressor Classic", "C 180 Kompressor Avantgarde", "C 180 AMG 9G-Tronic", "C 180 Classic", "C 200 Kompressor Sportcoupe", "C 180 Exclusive", "C 220 CDI BlueEFFICIENCY Fascination", "C 200 BlueTEC Avantgarde", "C 320 Avantgarde", "C 200 CDI Avantgarde", "C 180 Comfort 9G-Tronic", "C 270 CDI Elegance", "C 180 Kompressor Sportcoupe"),
        "C-Elysee" to listOf("1.5 BlueHDi Feel", "1.6 HDi Confort", "1.2 VTi Exclusive", "1.2 VTi Attraction", "1.6 BlueHDi Live", "1.6 HDi Shine", "1.6 HDi Attraction", "1.6 HDi Exclusive", "1.2 PureTech Live", "1.6 HDi Feel", "1.6 VTi Exclusive", "1.5 BlueHDi Feel Bold", "1.5 BlueHDi Shine", "1.6 BlueHDi Feel", "1.2 VTi Comfort", "1.6 HDi Live"),
        "C-Max" to listOf("1.6 Trend", "1.6 TDCi Trend", "1.6 TDCi Titanium X", "1.6 TDCi Titanium", "1.6 TDCi Ghia", "1.5 TDCi Titanium", "1.8 TDCi Trend", "1.6 Ghia", "1.6 SCTi Titanium", "1.6 SCTi Titanium Grand", "1.5 TDCi Trend"),
        "C1" to listOf("1.0 SX Sensodrive", "1.4 HDi SX"),
        "C2" to listOf("1.4 HDi SX", "1.4 SX", "1.4 HDi X Pack"),
        "C3" to listOf("1.4 HDi X Furio", "1.4 HDi SX", "1.2 PureTech Feel Bold", "1.4 HDi Attraction", "1.2 PureTech Feel", "1.4 HDi X", "1.4 X Furio", "1.4 SX", "1.4 HDi Exclusive", "1.4 HDi Confort", "1.2 PureTech Shine S Edition", "1.2 PureTech Shine", "1.2 PureTech Live", "1.6 SX", "1.4 VTi Collection", "1.2 VTi Cool", "1.6 BlueHDI Live", "1.6 HDi SX", "1.4 VTi Confort", "1.2 PureTech Feel Adventure", "1.4 Pluriel", "1.4 Comfort", "1.6 BlueHDI Feel", "1.6 VTi Feel", "1.4 Attraction", "1.2 PureTech Elle", "1.2 PureTech Feel S Edition", "1.4 e-HDi Confort", "1.6 BlueHDI Shine"),
        "C3 Picasso" to listOf("1.6 HDi SX", "1.6 e-HDi Confort"),
        "C30" to listOf("1.6 D Sports"),
        "C4" to listOf("1.4 SX", "1.6 HDi SX", "1.6 e-HDi Confort", "1.6 SX PK", "1.6 SX", "1.6 HDi Confort", "1.2 PureTech Feel Bold", "1.6 VTR", "1.6 HDi VTRPK", "1.4 VTi Attraction", "1.2 PureTech Shine", "1.6 e-HDi Exclusive", "1.6 e-HDi Confort Plus", "1.2 PureTech Shine Bold", "1.6 HDi Attraction", "1.6 HDi SX PK", "1.2 PureTech Feel", "1.6 HDi Confort Plus", "1.2 PureTech Confort", "1.6 VTI Confort", "1.6 BlueHDi Confort", "1.6 Collection", "2.0 VTS", "1.4 Collection"),
        "C4 Grand Picasso" to listOf("1.6 HDi Dynamic", "1.6 HDi SXPK", "1.6 e-HDi Dynamic", "1.6 BlueHDi Intensive", "1.6 e-HDi Intensive"),
        "C4 Picasso" to listOf("1.6 HDi SX PK", "1.6 HDi Dynamique", "1.6 BlueHDi Intensive", "1.6 e-HDi Intensive", "1.6 HDi VTR PK", "1.6 e-HDi Dynamic"),
        "C4 X" to listOf("1.2 PureTech Shine Bold", "1.2 PureTech Shine", "1.2 PureTech Feel Bold"),
        "C5" to listOf("1.6 HDi Executive", "1.6 HDi SX", "1.6 HDi SX PK", "1.6 HDi Dynamique", "1.6 e-HDi Confort", "1.6 e-HDi Executive", "2.0 HDi X", "1.6 e-HDi Dynamique", "2.0 HDi SX", "2.0 SX", "1.6 THP Dynamique", "1.6 HDi Confort", "2.0 HDi SX PK", "2.0 HDi Exclusive", "1.6 THP Exclusive"),
        "CLA" to listOf("180 D Urban", "180 CDI AMG", "200 AMG", "180 D AMG", "200 AMG+ 4Matic", "200 Urban", "180 D Comfort", "180 CDI Style"),
        "CLC" to listOf("160 Grand Prix"),
        "CLE" to listOf("300 AMG"),
        "CLK" to listOf("CLK 200 Kompressor Avantgarde", "CLK 200 Kompressor Elegance", "CLK 240 Avantgarde", "CLK 270 CDI Avantgarde", "CLK 430 Avantgarde", "CLK 230 Kompressor Avantgarde"),
        "CLS" to listOf("300 D AMG", "350", "350 D AMG", "250 CDI Sport"),
        "Cadenza" to listOf("3.5 GDI"),
        "Camry" to listOf("3.0 GX", "3.5", "2.4"),
        "Carens" to listOf("1.6 EX", "1.6 GSL"),
        "Carina" to listOf("2.0 GLi"),
        "Carisma" to listOf("1.8 GDI Elegance", "1.6 Avance", "1.6 GLX", "1.8 GDI LX", "1.9 DI-D Comfort", "1.6 GL", "1.6 Comfort"),
        "Carnival" to listOf("2.9 CRDi Premium"),
        "Ceed" to listOf("1.6 CRDi Concept Plus", "1.6 CRDi Cool", "1.4 Cool Tekno", "1.6 CRDi Concept Plus SW", "1.6 CRDi Premium", "1.6 CRDi Motion", "1.6 CRDi Comfort", "1.6 CRDi Concept", "1.0 Cool Tekno", "1.6 CRDi Concept SW", "1.5 T-GDI Elegance"),
        "Cerato" to listOf("1.6 MPI Elegance", "1.6 LX Basic", "1.6 CRDi EX", "1.6 EX Comfort", "1.6 CRDi Concept Plus", "1.5 CRDi LX", "1.5 CRDi EX", "1.6 CRDi Concept Techno", "1.6 GSL Core", "1.6 Koup", "1.6 CRDi Concept", "1.6 EX Premium", "1.6 EX Advance", "1.6 GSL Concept", "1.6 CRDi Comfort"),
        "Challenger" to listOf("SXT Plus"),
        "Chance" to listOf("1.6 Norma"),
        "City" to listOf("1.4 Sport", "1.5 i-VTEC Executive", "1.4 Comfort", "1.4 Elite", "1.4 ES", "1.4 LS"),
        "Civic" to listOf("1.4 i S", "1.6 i-VTEC LS", "1.6 i-VTEC Elegance", "1.6 i-VTEC ECO Elegance", "1.6 i-VTEC Eco Premium", "1.6 i ES", "1.6 i-VTEC Premium", "1.6 LS", "1.6 i-VTEC Eco Executive", "1.5 i-VTEC Eco Executive Plus", "1.6 i-DTEC Elegance", "1.6 Elegance", "1.6 i-VTEC ES", "1.5 i-VTEC Executive Plus", "1.5 i-VTEC RS", "1.6 Premium", "1.6 i-VTEC Dream", "1.5 i-VTEC Eco Elegance Plus", "1.4 1.4i", "1.6 i-VTEC Executive", "1.8 Sport", "1.5 i-VTEC Sport", "1.5 i-VTEC Eco Elegance", "1.6 i-VTEC Black Edition", "1.5 i-VTEC Eco Premium", "1.6 Dream", "1.6 i-DTEC Executive", "1.6 i-DTEC Comfort", "1.4 Sport", "1.6 i-DTEC Sport", "1.8 Executive", "1.5 i-VTEC Elegance", "1.6 i-DTEC Executive Plus", "1.4 S", "1.6 i-VTEC LS Elegance", "1.5 i-VTEC Sport Plus", "1.6 VTi", "1.6 Sport", "1.6 i LS"),
        "Clio" to listOf("1.0 TCe Techno Esprit Alpine", "1.0 TCe Evolution", "1.6 Dynamique", "1.5 dCi Joy", "1.5 dCi Authentique", "1.0 TCe Touch", "1.0 TCe Joy", "1.4 RNA", "1.4 RXT", "1.2 Joy", "0.9 TCe Joy", "1.5 dCi SportTourer Joy", "1.5 dCi Icon", "1.2 Authentique", "1.5 dCi SportTourer Icon", "1.4", "1.5 dCi Touch", "1.2 Expression", "1.5 BlueDCI Joy", "1.4 Dynamique", "1.5 dCi Extreme", "1.0 SCe Joy", "1.4 Alize", "1.0 TCe Icon", "1.4 Authentique", "1.6 RTE", "1.4 Extreme", "1.4 RN", "1.5 dCi Alize", "1.4 RTA", "1.4 RT", "1.5 dCi Grandtour Authentique", "0.9 TCe Icon", "1.2 Icon", "1.2 SportTourer Joy", "1.2 Grandtour Authentique", "1.2 Touchrome", "1.3 TCe Icon", "1.6 RXT", "1.5 dCi Grandtour Dynamique", "1.4 Expression", "1.5 dCi Expression", "0.9 TCe Touch", "1.2 Extreme", "1.3 TCe Touch", "1.5 dCi SportTourer Touch", "1.0 TCe Equilibre", "1.2 TCE Dynamique", "1.2 Touch", "1.2 Grandtour Extreme", "1.2 Turbo Icon", "1.2 Dynamic", "0.9 TCe Sport Tourer Joy", "1.5 dCi Grandtour Executive", "0.9 TCe Sport Tourer Touch", "1.5 dCi Authentique Edition", "1.2 Turbo Touchrome", "1.5 dCi Dynamique", "1.5 dCi Grandtour Extreme", "1.5 dCi Premiere", "1.4 Privilege", "1.2 Grandtour Night & Day", "1.5 dCi Night & Day", "1.5 dCi GT Line", "1.6 Grandtour Extreme", "1.0 SCe Equilibre", "1.5 dCi Fidji", "1.4 Fidji", "1.2 Tom Tom Edition", "1.2 Turbo Joy", "1.5 dCi Extreme Edition", "1.6 Extreme Edition", "1.0 TCe RS Line"),
        "Colt" to listOf("1.3 Inform", "1.3 Invite", "1.3 Elegance", "1.5 DI-D Inform", "1.1 Inform", "1.5 CZT", "1.5 Instyle"),
        "Cooper" to listOf("1.6 Türkiye Paketi", "1.5 D Pepper", "1.5 D Chili", "1.5 D Türkiye Paketi", "1.6", "1.6 D", "1.5 Signature", "1.5 D"),
        "Cooper Clubman" to listOf("1.6"),
        "Cooper S" to listOf("1.6"),
        "Cordoba" to listOf("1.4 Basic", "1.4 TDI Signo", "1.6 Signo", "1.4 Stella", "1.6 Stella", "1.9 TDI Signo", "1.4 TDI S-Rider", "1.6 SE", "1.4 TDI Stylance", "1.4 TDI Stella", "1.9 TDI Sport", "1.4 Stylance", "1.4 TDI Basic", "1.4 Signo", "1.4 TDI Elegance", "1.4 Elegance", "1.9 TDI SXE", "1.4 Sport"),
        "Corolla" to listOf("1.5 Dream", "1.6 Life", "1.6 Touch", "1.4 Terra", "1.4 D-4D Comfort", "1.6 Sol VVT-i", "1.8 Hybrid Dream", "1.33 Life", "1.6 Terra", "1.2 Turbo Dream X-Pack", "1.6 Comfort Extra", "1.4 D-4D Advance", "1.8 Hybrid Flame X-Pack", "1.6 Comfort", "1.6 Elegant", "1.5 Vision", "1.6 XEi", "1.5 Dream X-Pack", "1.4 D-4D Elegant", "1.6 Vision", "1.5 Flame X-Pack", "1.4 D-4D Sol", "1.6 Advance", "1.4 D-4D Premium", "1.6 Premium", "1.4 D-4D Touch", "1.6 Flame X Pack", "1.6 Sol", "1.3 Terra", "1.4 D-4D Class", "1.6 Elegant Verso", "1.5 Vision Plus", "1.6 Dream", "1.33 Comfort", "1.6 Verso", "1.6 Terra VVT-i", "1.6 Linea Terra", "1.3 ECO", "1.4 D-4D Comfort Extra", "1.6 Sol Special", "1.4 D-4D Terra", "1.6 Sol Plus", "1.6 Passion X-Pack", "1.8 Hybrid Passion X-Pack", "1.6 Plusline", "1.4 Terra VVT-i", "1.4 D-4D Life", "1.6 Linea", "1.6 Active", "1.6 Comfort Verso", "1.6 Linea Sol", "2.0 D-4D Comfort Extra Verso", "1.6 Luna Special", "1.6 Flame", "1.4 D-4D Linea", "1.6 Premium 50.Yıl", "1.6", "1.6 Terra Special", "1.4 D-4D Plusline", "1.6 Terra Special VVT-i", "1.6 Luna", "1.3 Base", "1.4 D-4D Active", "1.4 D-4D Premium 50.Yıl", "1.6 Comfort Extra Verso"),
        "Corsa" to listOf("1.4 GLS", "1.2 Twinport Essentia", "1.7 DTi Comfort", "1.4 Enjoy", "1.2 Elegance", "1.3 CDTI Enjoy", "1.2 Innovation", "1.2 Enjoy", "1.2 T GS", "1.4 Swing", "1.3 CDTI Enjoy 111", "1.4 Twinport Enjoy 111", "1.2 Swing", "1.2 Essentia", "1.4 Sport", "1.4 Twinport Active", "1.2 Twinport Enjoy", "1.3 CDTI Essentia", "1.4 Twinport Enjoy", "1.0 Eco Club", "1.2 Twinport Active", "1.2 Comfort", "1.0 Essentia", "1.5 CDTI Edition", "1.2 Turbo Edition", "1.3 CDTI Color Edition", "1.4 Comfort", "1.2 Turbo Ultimate", "1.4 Essentia", "1.4 Twinport Essentia", "1.3 CDTI Cosmo", "1.2 Twinport Enjoy 111", "1.4 Color Edition", "1.2 Turbo Elegance", "1.2 Edition", "1.2 Essential", "1.4 Design", "1.3 CDTI Sport", "1.2", "1.3 CDTI Active", "1.3 CDTI Silverline", "1.0 Enjoy", "1.5 TD", "1.4 Twinport Sport", "1.4 100.Yıl", "1.4 Silverline", "1.5 CDTI Innovation", "1.4 Twinport Cosmo", "1.2 Silverline", "1.4 CD", "1.4 Black Edition", "1.4 Twinport Color Edition", "1.4 Cosmo", "1.0 Comfort", "1.2 Club", "1.5 CDTI Dynamic", "1.4 Elegance", "1.4 120.Yıl", "1.2 Enjoy in Touch"),
        "Coupe" to listOf("2.0 FX", "2.0", "1.6 FX"),
        "Cruze" to listOf("1.6 LS", "1.6 LT Plus", "1.6 LT", "1.6 WTCC Edition", "1.6 LS Plus", "1.6 Sport Plus", "1.6 WTCC Edition Plus", "1.6", "2.0 D LT", "1.4 T Sport", "1.6 Design Edition", "1.6 Sport", "1.6 Design Edition Plus", "1.4 T LTZ", "1.4 T LT", "2.0 D LTZ"),
        "Cuore" to listOf("1.0 High Grade", "1.0 Low Grade"),
        "DS4" to listOf("1.5 BlueHDi Esprit de Voyage", "1.5 BlueHDi Performance Line", "1.6 e-HDi D-Sport", "1.5 BlueHDi Trocadero", "1.6 BlueHDi Standart"),
        "Delta" to listOf("1.6 MJet"),
        "Doğan" to listOf("1.6 ie", "S", "L", "SLX ie", "SL"),
        "E" to listOf("250 CDI Elite", "200 d Exclusive", "350 CDI Premium", "200 CGI BlueEFFICIENCY Elegance", "200", "220 CDI Avantgarde", "180 Edition E", "320 Elegance", "250 CDI BlueEFFICIENCY Avantgarde", "220 D AMG", "200 Classic", "200 Kompressor Avantgarde", "180 Elite", "250 CDI Premium", "250 CGI AMG Premium", "250 EditionE", "180 Exclusive", "220 D Exclusive", "200 Elegance", "200 d AMG", "250 CDI AMG", "250 CGI", "180 AMG", "200 Avantgarde", "200 Kompressor Classic", "270 CDI Elegance", "200 Kompressor Elegance", "180 AMG Premium", "200 CGI BlueEFFICIENCY Avantgarde", "250 CGI BlueEFFICIENCY Avantgarde", "180 Premium", "220 D Avantgarde", "250 CDI Elite Avantgarde", "240 Avantgarde", "230 Elegance", "250 AMG", "220 CDI Start", "300 D Exclusive", "320 Avantgarde", "320 CDI Avantgarde", "270 CDI Avantgarde", "250 Premium", "250 CDI Avantgarde", "200 CDI Elegance", "220 CDI Elegance", "240 Elegance", "290 TD Classic", "200 CDI Avantgarde", "320 CDI Elegance", "220 CDI Classic", "250 CDI Edition", "350 CDI Avantgarde", "300 D AMG"),
        "Echo" to listOf("1.3 Comfort"),
        "Egea" to listOf("1.4 Fire Urban Plus", "1.6 Multijet Lounge", "1.6 Multijet Easy", "1.4 Fire Urban", "1.4 Fire Easy", "1.4 Fire Lounge", "1.3 Multijet Easy", "1.3 Multijet Easy Plus", "1.6 Multijet Urban Plus", "1.3 Multijet Urban", "1.6 Multijet Easy Plus", "1.6 Multijet Urban", "1.4 Fire Easy Plus", "1.3 Multijet Urban Plus", "1.4 Fire Mirror", "1.4 Fire Street", "1.6 Multijet Limited", "1.6 Multijet Lounge Plus", "1.6 Multijet Mirror", "1.4 Fire Easy Stil", "1.6 E-Torq Lounge Plus", "1.6 Multijet Comfort", "1.3 Multijet Street", "1.0 Firefly Urban", "1.6 E-Torq Easy Plus", "1.6 E-Torq Lounge", "1.4 Fire Limited", "1.4 Fire Lounge Plus", "1.6 E-Torq Urban", "1.6 E-Torq Easy", "1.0 Firefly Lounge", "1.5 T4 Urban", "1.6 E-Torq Mirror", "1.3 Multijet Mirror"),
        "Elantra" to listOf("1.6 D-CVVT Tune", "1.6 MPI Style Comfort", "1.6 GLS", "1.6 MPI Style", "1.6 CRDi Elite Plus", "1.6 D-CVVT Style", "1.6 D-CVVT Mode Plus", "1.6 CRDi Elite", "1.6 Elegance", "1.6 D-CVVT Prime Plus", "1.6 CRDi Style", "1.6 MPI Elite", "2.0 CRDi GL", "1.8 GLS", "1.6 D-CVVT Mode", "1.6 D-CVVT Style Design Pack", "1.6 MPI Style Plus", "1.6 CRDi Style Plus", "1.6 MPI Elite Plus"),
        "Emgrand" to listOf("1.5 GSL Premium", "1.5 GSL", "1.5 GSL Premium SR"),
        "Epica" to listOf("D LT", "LT"),
        "Espace" to listOf("2.2 dCi Privilege", "2.0 T Expression"),
        "Evanda" to listOf("2.0 Platinum"),
        "Exeo" to listOf("1.6 Style", "1.6 Reference"),
        "FC" to listOf("1.5 GSL"),
        "Fabia" to listOf("1.6 TDI Ambiente", "1.4 Choice", "1.4 Ambiente", "1.4 TDI Ambiente", "1.2 Classic", "1.0 GreenTec Ambition", "1.0 GreenTec Style", "1.4 TDI Classic", "1.4 Classic", "1.6 TDI Scout", "1.2 Ambiente", "1.4 Comfort", "1.4 TDI Comfort", "1.2 TSI Style", "1.0 TSI Elite", "1.0 TSI Premium", "1.4 Special", "1.4 TDI Special", "1.6 TDI Optimal", "1.4 Elegance", "1.2 TSI Ambition", "1.2 Optimal", "1.2 Ambition", "1.6 TDI Ambiente Dinamik", "1.5 TSI Monte Carlo", "1.2 Elegance", "1.2 Choice", "1.0 Ambition", "1.0 GreenTec Premium", "1.4 TDI Style", "1.2 TSI Ambiente", "1.4 Optimal", "1.4 Ambiente Dynamic", "1.4 TDI Elegance", "1.2 Ambiente Dynamic", "1.4 Sport"),
        "Familia" to listOf("1.5 Comfort"),
        "Felicia" to listOf("1.3 LX", "1.3 GLXi", "1.3 LXi", "1.3", "1.6 GLXi", "1.6 GLXi Kombi"),
        "Fiesta" to listOf("1.5 TDCi Titanium", "1.25 Flair", "1.4 TDCi Titanium", "1.6 Trend X", "1.6 Titanium", "1.5 TDCi Trend X", "1.4 TDCi Comfort", "1.4 Comfort", "1.25 Ghia", "1.4 TDCi Trend", "1.25 Trend", "1.4 TDCi Collection", "1.25 My Fiesta", "1.5 TDCi Trend", "1.4 TDCi Titanium X", "1.4 Titanium", "1.4 Titanium X", "1.25 Trend X", "1.5 TDCi Titanium X", "1.6 TDCi Titanium", "1.4 Ghia", "1.6 Trend", "1.4 Fun", "1.6 Comfort", "1.4 Trend", "1.4 Collection", "1.0 Titanium", "1.0 GTDi Titanium", "1.4 Cool", "1.4 My Fiesta", "1.0 Style", "1.6 Ti-VCT Trend X", "1.1 Trend X", "1.4 TDCi My Fiesta", "1.1 Trend", "1.6 Sport", "1.6 TDCi Ghia", "1.4 TDCi Sport", "1.3 Flair", "1.4 TDCi Cool", "1.6 Ti-VCT Titanium", "1.1 Style", "1.6 TDCi Comfort", "1.6 Collection", "1.0 Trend"),
        "Fluence" to listOf("1.6 Extreme", "1.5 dCi Extreme", "1.5 dCi Touch", "1.5 dCi Icon", "1.5 dCi Business", "1.6 Expression", "1.5 dCi Touch Plus", "1.5 dCi Privilege", "1.5 dCi Extreme Edition", "1.6 Privilege", "1.6 Joy", "1.6 Business", "1.5 dCi Authentique", "1.5 dCi Joy", "1.6 Touch", "1.5 dCi Dynamique", "1.6 Dynamique", "1.6 Touch Plus", "1.5 dCi Bold Edition", "1.5 dCi Expression", "1.6 Icon"),
        "Focus" to listOf("1.6 TDCi Trend", "1.6 TDCi Style", "1.6 Ghia", "1.6 TDCi Collection", "1.5 Ti-VCT Trend X", "1.5 TDCi Trend X", "1.6 TDCi Trend X", "1.5 TDCi Titanium", "1.6 Comfort", "1.6 Ti-VCT Style", "1.6 TDCi Titanium", "1.6 Collection", "1.6 Ambiente", "1.6 Ti-VCT Trend X", "1.6 TDCi Ghia", "1.5 TDCi Titanium X", "1.6 Ti-VCT Titanium", "1.6 Trend X", "1.5 TDCi Style", "1.6 Trend", "1.6 Titanium", "1.5 TDCi Titanium Stil", "1.6 Ti-VCT Trend", "1.0 GTDi Titanium", "2.0 Sport Trend", "2.0 Ghia", "1.0 GTDi Trend X", "1.6 Ti-VCT Style Plus", "1.6 TDCi Titanium X", "1.5 Ti-VCT Titanium", "1.0 EcoBoost Titanium Stil", "1.6 Ti-VCT Collection", "1.5 TDCi Active X", "1.5 TDCi ST Line", "1.6 Titanium X", "1.6 TDCi Comfort", "1.0 EcoBoost Titanium X", "1.4 Comfort", "1.6 Gold Collection", "1.6 Darkline", "1.6 Ti-VCT Comfort", "1.5 TDCi Active Stil", "1.6 Ti-VCT Titanium X", "1.4 Trend", "1.8 TDCi Comfort", "1.5 TDCi Active"),
        "ForFour" to listOf("1.5 CDI Passion", "1.1 Passion", "1.0 Pure"),
        "ForTwo" to listOf("1.0 Passion"),
        "Fusion" to listOf("1.4 TDCi Comfort", "1.6 Lux", "1.4 TDCi Comfort ASM", "1.6", "1.4 TDCi 5K", "1.4 TDCi Trend", "1.6 TDCi Lux", "1.6 Comfort", "1.4 TDCi Urbanite", "1.4 TDCi Collection"),
        "Galaxy" to listOf("1.9 TDI"),
        "Gen 2" to listOf("1.6 Medium Line", "1.6 Low Line"),
        "Getz" to listOf("1.5 VGT Start", "1.4 DOHC Start", "1.5 CRDi VGT Start", "1.4 DOHC AB AC", "1.5 CRDi GL Cool", "1.5 CRDi GL Active", "1.4 DOHC HY KLM", "1.5 CRDi VGT", "1.3 GLS", "1.3 GLS Style", "1.5 VGT HY KLM", "1.6 Cool", "1.5 CRDi Active", "1.5 CRDi Classic", "1.5 CRDi Comfort Plus"),
        "Ghibli" to listOf("3.0"),
        "Giulietta" to listOf("1.6 JTD Progression", "1.6 JTD Distinctive", "1.4 TB MultiAir Distinctive", "1.4 TB Progression Plus", "1.6 JTD Progression Plus", "1.6 JTDM-2 Super"),
        "Golf" to listOf("1.4 TSi Highline", "1.4 TSi Trendline", "1.6 TDi BlueMotion Comfortline", "1.5 TSi Highline", "1.6 TDi BlueMotion Highline", "1.0 eTSI Life", "1.6 TDi BlueMotion Midline Plus", "1.6 Comfortline", "1.2 TSi Midline Plus", "1.0 TSi Highline", "1.6 Midline Plus", "1.9 TDi", "1.6 TDi Highline", "1.6 FSi Comfortline Plus", "1.6 TDi Comfortline", "1.6 FSi Comfortline", "1.6 Primeline", "1.6 Midline", "1.6 TDi Trendline", "1.5 TSi Comfortline", "1.6 Trendline", "1.5 TSi Impression", "1.2 TSi Comfortline", "1.4 TSi Comfortline", "1.6 FSi Midline Plus", "1.6 FSi Midline", "1.0 TSi Comfortline", "1.6", "1.6 TDi Allstar", "1.6 Pacific", "1.9 TDi Comfortline", "1.5 eTSI R Line", "1.4 TSi Midline", "1.6 Goal", "1.6 FSi Sportline", "1.0 TSi Midline Plus", "1.8 Highline", "1.6 FSi Goal", "1.8 GTI", "1.0 TSi Impression", "1.0 eTSI R Line", "1.0 eTSI Style", "1.6 Basic", "1.5 eTSI Style", "1.5 eTSI Life", "1.6 Tour", "1.4 TSi Tour", "1.6 TDi BlueMotion", "1.6 Highline", "1.4 TSi Pulse", "1.6 FSi Primeline", "1.9 TDi Midline"),
        "Grand C-Max" to listOf("1.6 TDCI Titanium"),
        "Grand Scenic" to listOf("1.5 dCi Privilege", "1.5 dCi Authentique", "1.5 dCi Expression"),
        "Ibiza" to listOf("1.4 Stella", "1.0 Style", "1.4 Sport Tourer Style", "1.4 Reference", "1.0 Referance", "1.4 Style", "1.0 EcoTSI Style", "1.2 TSI Style", "1.0 EcoTSI FR", "1.4 TDI Stylance", "1.4 TDI Signo", "1.2 TSI Reference", "1.2 TSI Sport Tourer Style", "1.6 Stella", "1.4 Signo", "1.4 SE", "1.4 Sport Tourer Copa", "1.6 Elegance", "1.2 TDI Sport Tourer Reference", "1.6 TDI CR Reference", "1.6 Signo", "1.4 TDI S-Rider", "1.2 Reference", "1.4 TDI Style", "1.4 TDI Reference", "1.4 Elegance", "1.6 Style", "1.4 Stylance"),
        "Idea" to listOf("1.4 Active", "1.4 Dynamic Plus", "1.3 Multijet Active", "1.4 Dynamic"),
        "Impreza" to listOf("1.6 GL", "1.5 AWD", "1.5 Active", "1.5 Comfort", "2.5 WRX"),
        "Indica" to listOf("1.4 DLX", "1.4 TDI Trend", "1.4 TDI Comfort", "1.4 Basic"),
        "Indigo" to listOf("1.4 TDI Comfort", "1.4 TDI Trend", "1.4 MPFI Comfort"),
        "Insignia" to listOf("1.6 T Edition Elegance", "1.4 T Edition Elegance", "1.6 CDTI Grand Sport Excellence", "1.6 CDTI Cosmo", "1.5 d Edition", "2.0 CDTI Edition", "2.0 CDTI Cosmo Active Select", "1.6 CDTI Exclusive Grand Sport", "2.0 CDTI Cosmo", "1.6 T Cosmo", "1.6 CDTI Grand Sport Enjoy", "1.6 CDTI Sport", "1.6 T Edition", "1.6 Edition", "1.5 d Elegance", "1.6 CDTI Grand Sport Design", "2.0 CDTI Edition Elegance", "1.6 CDTI Edition Elegance", "1.6 CDTI Design", "1.6 CDTI Grand Sport Elite", "1.6 Cosmo", "1.6 CDTI Business", "1.5 T Grand Sport Edition Özel Seri", "1.6 CDTI Elite", "1.6 CDTI Excellence", "1.5 T Grand Sport Excellence", "2.0 CDTI CDTi", "1.6 CDTI Enjoy", "1.6 T Sport"),
        "Ioniq" to listOf("1.6 GDI Hybrid Progressive"),
        "Jazz" to listOf("1.4 ES", "1.4 Joy", "1.4 ES Elite", "1.4 LS", "1.4 Fun", "1.4 LS Sport", "1.3 Elegance", "1.5 Hybrid Advance"),
        "Jetta" to listOf("1.6 Primeline", "1.6 TDi Comfortline", "1.4 TSi Trendline", "1.4 TSi BlueMotion Comfortline", "1.6 Midline", "1.2 TSi BlueMotion Trendline", "1.6 TDi Highline", "1.6 Comfortline", "1.4 TSi Comfortline", "1.6 TDi Trendline", "1.6 Exclusive", "1.2 TSi Trendline", "1.6 Tour", "1.6 TDi Exclusive", "1.6 FSi Comfortline", "1.2 TSi BlueMotion Highline", "2.0 TDi Comfortline", "1.2 TSi BlueMotion Comfortline", "1.2 TSi Comfortline", "1.6 TDi Primeline", "1.9 TDi Midline", "1.2 TSi Highline", "1.4 TSi Highline", "1.9 TDi Primeline", "1.4 TSi BlueMotion Highline", "1.4 TSi Midline", "1.4 TSi Exclusive", "1.6 FSi Midline", "1.4 TSi BlueMotion Trendline", "1.4 TSi Tour", "1.6 TDi Midline"),
        "Jogger" to listOf("1.0 Eco-G Expression", "1.0 Eco-G Extreme"),
        "Ka" to listOf("1.3", "1.2 Titanium", "1.3 City", "1.3 TDCi Trend"),
        "Kalina" to listOf("1.6"),
        "Kalos" to listOf("1.4 SX", "1.2 SE", "1.2 S", "1.4 SE"),
        "Kartal" to listOf("S"),
        "Kimo" to listOf("1.3 Forza", "1.3 Lusso"),
        "Lacetti" to listOf("1.6 SX", "1.4 SE", "1.6 WTCC", "1.4 SX", "1.6 CDX"),
        "Laguna" to listOf("1.5 dCi Privilege", "1.6 Privilege", "2.0 RXE", "1.6 Expression", "2.0 RXT", "1.9 DTi RXE", "1.5 dCi Expression", "2.0 Privilege", "1.6 Authentique", "1.8 RXE", "1.6 RXE", "2.0 dCi Privilege", "2.0 T Privilege", "1.9 dCi Privilege", "2.0 dCi Sport Emotion", "1.9 dCi Expression", "1.8 Privilege", "1.5 dCi Dynamique", "1.8 RT", "1.5 dCi Executive", "2.0 dCi Dynamique", "1.6 Dynamique", "2.0 Dynamique"),
        "Lancer" to listOf("1.6 Invite", "1.6 Comfort", "1.5 Invite", "1.5 Inform"),
        "Lanos" to listOf("1.6 SX", "1.5 SE"),
        "Latitude" to listOf("1.5 dCi Executive", "1.5 dCi Expression", "2.0 dCi Executive", "1.5 dCi Privilege", "2.0 dCi Privilege"),
        "Laurel Altima" to listOf("2.0"),
        "Legacy" to listOf("2.0 Limited", "2.0 SportWagon"),
        "Leganza" to listOf("2.0 SX"),
        "Legend" to listOf("3.5"),
        "Leon" to listOf("1.4 EcoTSI Xcellence", "1.6 TDI CR Style", "1.6 TDI Style", "1.6 TDI Xcellence", "1.5 eTSI", "1.2 TSI Style", "1.4 EcoTSI FR", "1.5 EcoTSI FR", "1.4 TSI Style", "1.6 Stylance", "1.4 TSI FR", "1.6 Style", "1.5 EcoTSI Xcellence", "1.5 eTSI FR", "1.0 eTSI Style", "1.0 TSI Style", "1.6 Reference", "1.6 TDI FR", "1.6 Signo", "1.4 TSI Stylance", "1.0 EcoTSI Ecomotive Style", "1.6 Stella", "1.6 Sport", "1.9 TDI Signo", "1.0 eTSI Style Plus", "1.6 TDI Sport Tourer Style", "1.4 TSI Copa Plus"),
        "Liana" to listOf("1.6 GLX"),
        "Linea" to listOf("1.3 Multijet Active Plus", "1.3 Multijet Actual", "1.4 Turbo Dynamic", "1.6 Multijet Urban", "1.3 Multijet Easy", "1.3 Multijet Pop", "1.6 Multijet Emotion Plus", "1.4 Fire Pop", "1.3 Multijet Active", "1.4 Fire Actual", "1.4 Fire Actual Plus", "1.4 Fire Active Plus", "1.3 Multijet Actual Plus", "1.6 Multijet Easy", "1.4 Fire Active", "1.3 Multijet Lounge", "1.3 Multijet Mood", "1.4 Fire Dynamic", "1.6 Multijet Active Plus", "1.3 Multijet Dynamic", "1.3 Multijet Urban", "1.3 Multijet Emotion", "1.6 Multijet Lounge", "1.4 Fire Easy", "1.6 Multijet Emotion", "1.4 Turbo Active", "1.3 Multijet Dynamic Plus", "1.6 Multijet Dynamic Plus", "1.3 Multijet Emotion Plus", "1.6 Multijet Dynamic", "1.4 Turbo Emotion", "1.4 Turbo Emotion Plus", "1.3 Multijet VIA"),
        "Lodgy" to listOf("1.5 dCi Laureate", "1.5 dCi Stepway", "1.5 BlueDCI Ambiance", "1.5 BlueDCI Stepway", "1.5 BlueDCI Laureate"),
        "Logan" to listOf("1.2 Ambiance", "1.5 dCi MCV Black Line", "1.5 dCi MCV Ambiance", "1.4 Ambiance", "1.2", "1.6 Laureate", "1.4 Laureate", "1.6 Ambiance", "1.5 dCi Ambiance", "1.4", "1.5 dCi Laureate", "0.9 Tce Ambiance", "1.5 dCi Black Line"),
        "Manza" to listOf("Aura 1.4 Safire"),
        "Marea" to listOf("1.6 Liberty", "1.6 ELX", "1.6 SX", "2.0 HLX", "1.6 Exclusive"),
        "Marina" to listOf("1.4 TDI Comfort", "1.4 TDI Trend"),
        "Maruti" to listOf("800"),
        "Materia" to listOf("1.5 Gold"),
        "Matiz" to listOf("0.8 SE"),
        "Matrix" to listOf("1.6 Team", "1.6 Start", "1.5 CRDi Team", "1.5 CRDi GLS", "1.5 CRDi Select", "1.5 CRDi Start", "1.6 GLS", "1.5 CRDi GL", "1.5 CRDi VGT GLS", "1.6 Style", "1.6 GL", "1.6 Select", "1.5 CRDi Style"),
        "Maxima" to listOf("2.0 QX"),
        "Megane" to listOf("1.3 TCe Joy Comfort", "1.5 Blue DCI Icon", "1.5 dCi Dynamique", "1.5 dCi Privilege", "1.5 Blue DCI Touch", "1.5 dCi Play", "1.5 dCi Authentique", "1.4 Authentique", "1.5 dCi Icon", "1.5 dCi Touch", "1.3 TCe Joy", "1.5 dCi Joy", "1.9 DTi RTE", "1.6 Joy", "1.6 Dynamique", "1.5 dCi Touch Plus", "1.5 dCi Expression", "1.5 Blue DCI Joy", "1.6 Expression", "1.6 RXE", "1.5 Blue DCI Joy Comfort", "1.5 dCi Sport Tourer Privilege", "1.5 dCi GT-Line", "1.5 dCi Sportway", "1.3 TCe Touch", "1.6 RTE", "1.6 RXT", "1.6 Alize", "1.4 RTA", "2.0 RXE", "1.6 Sportway", "1.6 CC Privilege", "1.5 dCi Extreme", "1.3 TCe Icon", "1.9 DTi Expression", "1.5 dCi Sport Edition", "1.6 Authentique", "1.6 Touch Plus", "1.6 RXi", "1.6 Extreme", "1.6 CC Dynamique", "2.0 RXT", "1.6 Privilege", "1.6 Business", "1.6", "1.5 dCi Impressor", "1.2 TCe Touchrome", "1.6 RTA", "1.6 Coupe Dynamique", "1.5 dCi Joy Plus", "1.6 Touch", "1.2 TCe Icon", "2.0 T Sport", "1.6 RNA", "1.6 Coupe RXI", "1.0 TCe Joy", "1.6 Coupe RN", "1.6 Coupe Expression", "1.6 dCi Icon", "1.5 dCi Exception", "1.6 Cabrio Cabrio", "1.9 dCi Alize", "1.6 Exception", "2.0 Dynamique", "1.6 Icon", "1.2 TCe Touch", "1.6 Coupe RXE", "1.5 dCi Sport Tourer GT-Line", "1.4 Premiere", "1.5 dCi Business", "1.9 dCi Privilege", "1.6 dCi GT-Line Energy", "1.5 dCi Sport Tourer Expression", "1.5 dCi Color Edition", "1.6 Sport Tourer Expression", "1.6 Coupe 1.6 e", "1.4 Base", "1.6 dCi GT-Line Energy Sport Tourer", "1.4 T Impressor", "1.6 Grandtour Dynamique", "1.4 Expression"),
        "Meriva" to listOf("1.6 Essentia", "1.6 Cosmo", "1.3 CDTI Enjoy", "1.3 DTI Essentia", "1.6 Enjoy", "1.3 CDTI Essentia", "1.4 T Enjoy", "1.4 T Cosmo", "1.7 CDTI Enjoy", "1.3 CDTI Cosmo", "1.7 CDTI Cosmo", "1.3 CDTI EcoFlex Enjoy"),
        "MiTo" to listOf("1.3 JTD City"),
        "Micra" to listOf("1.2 Passion", "1.2 Tekna", "1.2 Punch", "1.3 GX", "1.2 Street", "1.2 Match", "1.0 IG-T Tekna", "1.2 Visia", "1.3 Magic", "1.2 Mood", "1.2 Platinum", "1.0 IG-T Visia"),
        "Modus" to listOf("1.4 Authentique", "1.4 Dynamique", "1.6 Authentique", "1.5 dCi Dynamique", "1.5 dCi Authentique"),
        "Mondeo" to listOf("2.0 GLX", "1.6 Titanium", "1.5 Ecoboost Titanium", "1.8 Ambiente", "2.0 Ghia", "1.6 Trend", "1.6 Selective", "2.0 TDCi Titanium", "1.6 TDCi Titanium", "2.0 TDCi Ghia", "1.5 Ecoboost Style", "2.0 Trend", "2.0 TDCi Selective", "2.0 Selective", "2.0 TDCi Trend", "2.5 Ghia", "1.6 TDCi Selective", "2.0 TDCi Titanium X", "1.5 TDCi Titanium", "1.6 Ecoboost Selective", "1.6 TDCi Trend"),
        "Move" to listOf("1.5 Gran Move"),
        "New Beetle" to listOf("1.2 TSi Design", "1.4 TSi Design", "1.9 TDi", "2.0 Diamond"),
        "Niche" to listOf("2.0 Lusso"),
        "Note" to listOf("1.4 Tekna", "1.6 Tekna", "1.4 Visia", "1.5 dCi Tekna", "1.6 Visia", "1.5 dCi Tekna Pack", "1.2 Visia", "1.2 Tekna"),
        "Nubira" to listOf("1.6 S", "1.6 SX"),
        "Octavia" to listOf("1.0 e-Tec Elite", "1.6 TDI Optimal", "1.6 TDI Elegance CR", "1.4 TSI Sport", "1.6 Ambiente", "1.6 TDI Style", "1.6 Classic", "1.5 e-Tec Premium", "1.6 FSI Elegance", "1.6 Elegance", "1.5 e-Tec Sportline", "1.6 TDI Ambition", "1.2 TSI Style", "1.6 TDI Elegance", "1.4 TSI Elegance", "1.6 TDI Ambiente", "1.6 TDI Style CR", "1.5 e-Tec Elite", "1.2 TSI Ambition", "1.2 TSI Elegance", "1.6 Collection Plus", "1.4 TSI Ambiente", "1.6 Tour", "1.8 T L&K", "1.0 e-Tec Premium", "1.9 TDI Tour", "1.0 TSI Ambition", "1.5 Mhev Premium", "1.9 TDI Elegance", "1.6 TDI Ambition Optimal", "1.6 Active", "1.6 FSI Ambiente", "1.6 Ambiente Optimal", "1.6 GLX", "1.9 TDI Ambiente", "1.6 TDI Classic", "1.5 TSI Style"),
        "Omega" to listOf("2.0 CD", "3.0 3.0 MV6"),
        "Palio" to listOf("1.4 EL", "1.2 EL", "1.2 HL", "1.6 HL", "1.2 Go", "1.2 SL", "1.6 HL Weekend", "1.2 Active", "1.4 HL", "1.2 HL Speedgear", "1.3 Multijet Active", "1.4 Fire Premio Sole", "1.2 S Weekend", "1.3 Multijet Active Sole", "1.2 S", "1.3 Multijet EL", "1.3 Multijet SL", "1.2 Dynamic Speedgear", "1.3 Multijet Dynamic", "1.2 EL Speedgear", "1.4 Fire Dynamic Sole", "1.2 Dynamic", "1.2 EL Weekend", "1.3 Multijet Dynamic Sole", "1.4 Fire Active Sole", "1.4 RT", "1.4 Fire Dynamic", "1.4 Fire Active", "1.2 Feel", "1.3 Multijet Premio Sole"),
        "Panamera" to listOf("Diesel"),
        "Panda" to listOf("1.2 Dynamic", "1.2 Pop", "1.2 Fire Urban", "1.2 Active", "0.9 TwinAir Pop", "1.0 Hybrid Cross"),
        "Passat" to listOf("1.6 FSi Comfortline", "2.0 TDi Highline", "1.6 TDi BlueMotion Impression", "1.6 TDi BlueMotion Comfortline", "1.4 TSi BlueMotion Comfortline", "1.5 TSi Elegance", "1.5 TSi Business", "1.6 TDi Business", "2.0 TDi BlueMotion Comfortline", "1.6 TDi BlueMotion Trendline", "1.4 TSi BlueMotion Trendline", "1.6 TDi BlueMotion Business", "1.4 TSi Comfortline", "2.0 FSi Highline", "1.6 TDi BlueMotion Exclusive", "1.6 TDi BlueMotion Highline", "1.6 Trendline", "1.6 Comfortline", "1.4 TSi Trendline", "2.0 TDi BlueMotion Highline", "1.4 TSi BlueMotion Highline", "1.8 T Basic", "1.9 TDi Comfortline", "1.6", "1.8 T Comfortline", "2.0 TDi BlueMotion Business", "1.8 Comfortline", "1.8 Trendline", "2.0 TDi Comfortline", "1.8 Basic", "1.8 Highline", "1.8 T Highline", "2.0 FSi Comfortline", "1.5 TSi Impression", "1.9 TDi", "1.6 FSi Exclusive", "1.6 TDi BlueMotion R Line", "1.6 TDi BlueMotion", "2.0", "1.6 FSi Trendline", "1.4 TSi Exclusive", "1.8 TSi Comfortline", "1.6 TDi BlueMotion Elegance", "1.6 TDi", "2.0 TDi Exclusive", "2.8 Highline", "1.6 Exclusive", "1.4 TSi BlueMotion Exclusive", "1.9 TDi Exclusive", "2.0 Comfortline", "2.5 TDi Comfortline", "1.8 T", "1.9 TDi Highline", "2.0 TDi Elegance", "1.4 TSi Highline", "1.9 TDi Basic", "1.8 TSi Exclusive", "1.8 TSi Highline"),
        "Passat Variant" to listOf("1.6 TDi BlueMotion Comfortline", "2.0 TDi Highline", "1.4 TSi BlueMotion Comfortline", "1.9 TDi Comfortline", "1.5 TSI Business", "1.6 TDi BlueMotion Highline", "1.5 TSI Elegance"),
        "Phaeton" to listOf("3.0 TDi"),
        "Picanto" to listOf("1.1 EX", "1.2 MPI Feel", "1.0 MPI", "1.25 EX", "1.1 Hiper"),
        "Polo" to listOf("1.0 Trendline", "1.6", "1.6 TDi Comfortline", "1.4 TDi Trendline", "1.4 TDi Comfortline", "1.0 TSi Comfortline", "1.4 Comfortline", "1.4 Trendline", "1.4 TDi Bluemotion", "1.4 Highline", "1.0 Impression", "1.2 Trendline", "1.6 Classic", "1.0 Style", "1.2 TSi Allstar", "1.2 TDi Trendline", "1.2 TSi Comfortline", "1.4 Basicline", "1.2 TSi Lounge", "1.0 TSi Highline", "1.6 Comfortline", "1.6 TDi Trendline", "1.4 TDi Goal", "1.4 Chrome Edition", "1.6 Comfortline Classic", "1.4 TDi", "1.4 Cross", "1.2 TDi BlueMotion", "1.4 Sportline", "1.4 TDi Basicline", "1.4 TDi Primeline", "1.4", "1.4 Goal", "1.6 Trendline Variant", "1.4 Tour", "1.6 Variant", "1.4 TDi Tour", "1.9 SDi Comfortline", "1.9 TDi", "1.4 Fan Edition", "1.6 Trendline Classic", "1.0 Life"),
        "Pride" to listOf("1.3 DLX", "1.3"),
        "Primera" to listOf("1.6 Tekna", "1.6 Comfort", "2.0 SE", "1.6 SLX", "1.6 GX", "1.6 Special Edition", "1.6 Tekna Plus", "2.0 TD Elegance", "2.0 Elegance", "1.6 LX", "2.0 TD Luxe", "1.6 Visia"),
        "Pro Ceed" to listOf("1.6 CRDi Concept", "1.6 CRDi Cool Plus"),
        "Pulsar" to listOf("1.2 Tekna", "1.5 N-Tec"),
        "Punto" to listOf("Grande 1.4 Fire Active", "1.4 Dynamic", "EVO 1.3 Multijet Active", "Grande 1.3 Multijet Active", "Grande 1.4 Fire Dynamic", "EVO 1.4 Dynamic", "EVO 1.4 Fire Dynamic", "1.4 Easy S&S", "1.3 Multijet Pop", "1.2 Dynamic", "Grande 1.3 Multijet Dynamic", "1.3 Multijet Dynamic", "1.4 Popstar S&S", "EVO 1.4 Active", "1.4 Lounge S&S", "Grande 1.4 T-Jet Dynamic", "EVO 1.3 Multijet Dynamic", "Grande 1.4 Starjet Dynamic", "1.2 Pop", "1.3 Multijet Lounge", "1.4 Pop S&S", "1.3 Multijet Urban", "1.3 Multijet Easy", "Grande 1.3 Multijet Emotion", "1.3 Multijet Popstar", "1.2 Popstar", "Grande 1.3 Multijet 1.3 Multijet", "Grande 1.4 Fire S&S", "1.4 Mair Easy S&S", "EVO 1.4 Fire My Life", "EVO 1.3 Multijet My Life", "Grande 1.4 T-Jet Sport", "EVO 1.4 Multiair Dynamic", "Grande 1.3 Multijet Fun", "1.3 Multijet Shine", "Grande 1.4 Fire Fun", "Grande 1.2 S5"),
        "Q30" to listOf("1.6"),
        "RCZ" to listOf("1.6 THP Evolution", "1.6 THP Yearling"),
        "Rapid" to listOf("1.2 TSI Ambition", "1.6 TDI Spaceback Elegance", "1.4 TDI Ambition", "1.6 TDI Elegance", "1.4 TDI GreenTec Style", "1.2 Spaceback Ambition", "1.6 TDI Active", "1.6 TDI Ambition", "1.0 TSI GreenTec Style", "1.2 Ambition", "1.2 TSI Spaceback Elegance", "1.0 TSI GreenTec Ambition", "1.2 TSI GreenTec Style", "1.4 TDI GreenTec Ambition"),
        "Rezzo" to listOf("1.6 SX Comfort"),
        "Rio" to listOf("1.5 CRDi EX Comfort", "1.25 CVVT Fancy", "1.5 Comfort", "1.4 CVVT Fancy", "1.4 GSL Trend", "1.4 CVVT Cool", "1.4 CVVT Comfort", "1.4 CRDi Concept", "1.5 CRDi Trend", "1.5 CRDi EX Advance", "1.4 CRDi Fancy", "1.4 CRDi Concept Plus", "1.4 CRDi Natty", "1.4 CRDi Sporty", "1.4 WGT Cool", "1.4 EX Comfort", "1.4 CRDi Comfort", "1.25 CVVT Cool", "1.4 CVVT Concept", "1.25 CVVT Concept", "1.3 Comfort", "1.4 WGT Elegance", "1.4 EX Advance", "1.25 CVVT Comfort", "1.5 Trend", "1.25 CVVT Natty", "1.3 Trend", "1.4 CVVT Natty", "1.4L MPI Elegance", "1.3 Base", "1.25 CVVT Elegance Tekno"),
        "Roomster" to listOf("1.2", "1.2 Style", "1.2 Dinamik", "1.6 TDI Active", "1.4 TDI", "1.4 TDI Comfort", "1.2 TSI Style", "1.4 TDI Style", "1.6 Comfort"),
        "S" to listOf("S 450 450 D Inspration", "S 400 400 d AMG", "S 350 350 BlueTEC", "S 320 320 CDI", "S 320 320 L", "S 350 350 L", "S 320 320", "S 500 500 L"),
        "S-Max" to listOf("2.0 TDCi Titanium"),
        "S-Type" to listOf("2.7 D Executive"),
        "S40" to listOf("1.6 D", "2.0", "1.8", "1.6", "1.6 D Dynamic", "1.9 T4", "1.6 D Premium", "1.6 D Prime", "2.0 T", "1.6 Premium", "1.6 D R-Design", "1.6 Dynamic", "1.6 Prime"),
        "S60" to listOf("1.6 D Advance", "1.6 D Premium", "2.0 T Premium", "1.5 T3 Premium", "2.0 T", "2.0 D Advance", "1.6 T4 Premium", "1.6 D R-Design", "1.5 T3 Advance", "1.6 T4 Advance", "2.0 D Premium", "1.6 T4 R-Design", "2.4 D"),
        "S80" to listOf("1.6 D", "2.5 T", "2.0 T", "2.4 D5", "1.6 D Advance", "1.6 D Premium", "2.8 T6", "2.9"),
        "S90" to listOf("2.0 D5 Inscription", "2.0 D4 Momentum"),
        "SLK" to listOf("200 Kompressor"),
        "SX4" to listOf("GLX", "GL"),
        "Safrane" to listOf("2.0 RXE", "2.0"),
        "Samand" to listOf("1.6 LX"),
        "Samara" to listOf("1.5"),
        "Sandero" to listOf("1.5 dCi Stepway Style", "1.5 dCi Ambiance", "1.2 Ambiance", "1.0 Tce Prestige", "0.9 TCe Stepway Easy-R", "1.5 dCi Stepway", "0.9 TCe Stepway Ambiance", "1.0 Ambiance", "1.5 BlueDCI Stepway", "1.4 Ambiance", "1.0T ECO-G Comfort", "0.9 TCe Stepway", "1.4 Laureate", "1.0 Tce Comfort", "1.6 Stepway", "1.4 Black Line", "1.0 Stepway", "1.0 Tce Extreme", "1.5 dCi Black Line", "1.6 Laureate", "0.9 TCe Stepway Style"),
        "Saxo" to listOf("1.4 SX", "1.5D SX", "1.6 VTS", "1.6 VTR", "1.6 SX"),
        "Scala" to listOf("1.6 TDI Premium", "1.0 TSI Premium", "1.5 TSI Monte Carlo", "1.0 TSI Comfort"),
        "Scenic" to listOf("2.0 RXT", "1.6 RXT", "1.6 RXE", "1.6 Dynamique", "1.5 dCi Dynamique", "1.6 Privilege", "1.5 dCi Privilege", "1.6", "1.6 Authentique", "1.6 RTE", "1.6 Expression", "1.5 dCi Expression", "1.5 dCi Exception", "1.5 dCi Icon", "1.9 dCi Dynamique", "1.6 Exception", "2.0 Privilege", "1.9 dCi Privilege"),
        "Scirocco" to listOf("1.4 TSi Sportline", "1.4 TSi Allstar"),
        "Sebring" to listOf("2.0 CRD Convertible", "2.0 CRD Limited", "2.7 LX"),
        "Sephia" to listOf("1.5 LS", "1.5 GTX"),
        "Sharan" to listOf("1.9 TDI Comfortline"),
        "Shuma" to listOf("LS", "RS"),
        "Sirion" to listOf("1.0", "1.3 Sporty", "1.3", "1.3 Touring"),
        "Solenza" to listOf("1.4 Rapsodie", "1.4 Scala", "1.4 Clima"),
        "Sonata" to listOf("2.0 GLS", "2.0 CRDi Style", "2.0 CRDi H-Matic"),
        "Space Star" to listOf("1.2 MIVEC", "1.2 Invite"),
        "Spark" to listOf("1.0 SX", "1.0 SE", "0.8 S", "0.8 SE", "1.2 LTZ", "1.0", "1.2 LT"),
        "Splash" to listOf("1.2 GLS"),
        "Starlet" to listOf("1.3 XLi", "1.3", "1.3 XLi Plus"),
        "Stilo" to listOf("1.4 Active", "1.6 Dynamic", "1.9 JTD Dynamic", "1.6 Dynamic MultiWagon", "1.6 Active", "1.6 Actual"),
        "Stratus" to listOf("2.5 LX"),
        "SuperB" to listOf("2.0 TDI Laurin&Klement", "1.6 TDI Prestige", "1.6 TDI Elite", "1.6 TDI Style", "1.6 TDI Comfort", "1.5 TSI Prestige", "1.4 TSI Active", "1.4 TSI Ambition", "1.8 T Comfort", "2.5 TDI Elegance", "2.0 TDI Prestige", "1.6 TDI Premium", "1.6 TDI Active", "1.6 TDI Ambition", "1.6 TDI Elegance", "1.4 TSI Style", "1.4 TSI Comfort", "1.5 TSI Premium", "1.9 TDI Elegance", "1.9 TDI Comfort", "1.4 TSI Elegance", "1.5 TSI Elite", "1.5 TSI Active", "2.0 TDI Elegance", "1.5 TSI L&K Crystal", "1.4 TSI Prestige"),
        "Swift" to listOf("1.2 GL", "1.3 GLX", "1.3 MT 4X4", "1.5 AT", "1.3 MT", "1.2 GLX"),
        "Symbol" to listOf("1.5 dCi Joy", "1.0 SCe Joy", "1.2 Joy", "1.4 Authentique", "0.9 TCe Joy", "1.2 Authentique", "1.5 dCi Extreme", "1.2 Touch", "1.5 dCi Expression", "1.4 Expression Plus", "1.2 Expression", "1.2 Authentique Edition", "1.4 Expression", "1.5 dCi Authentique", "1.5 dCi Touch", "1.2 Expression Plus", "1.5 dCi Expression Plus", "1.4 Dynamique", "1.5 dCi BlueDCI Joy", "0.9 Turbo Touch", "1.0 SCe Touch", "1.0 TCe Joy", "1.5 dCi Dynamique", "1.5 dCi Authentique Edition", "0.9 Joy"),
        "TT" to listOf("2.0 TFSI", "2.0 TDI Quattro"),
        "Taliant" to listOf("1.0 Tce Joy", "1.0 Tce Touch"),
        "Talisman" to listOf("1.6 dCi Touch", "1.6 dCi Icon", "1.5 dCi Touch", "1.5 dCi Icon"),
        "Tempra" to listOf("1.6 SX SW", "1.6 SW AK", "1.6 SX AK SW"),
        "Thema" to listOf("3.0 CRD"),
        "Tico" to listOf("0.8 SL"),
        "Tigra" to listOf("1.6"),
        "Toledo" to listOf("1.6 Signo", "1.6 TDI Style", "1.4 TDI Style", "1.6 Reference", "1.2 TSI Style", "1.2 TSI Reference", "1.6 Stella", "1.6 Signo Plus", "1.9 TDI Sport", "1.6 Signum", "1.8 Signo"),
        "Touran" to listOf("1.9 TDi Highline", "1.6 FSi Highline", "1.6 Function", "1.4 TSi Comfortline", "2.0 TDi Highline"),
        "Twingo" to listOf("1.2 Alize"),
        "Urban Cruiser" to listOf("1.33 Elegant"),
        "V40" to listOf("1.5 T3 Inscription", "1.5 T3 Advance", "1.6 D", "1.5 T3 Momentum", "1.6 D Advance", "1.6 D R-Design", "1.6 T4 Advance"),
        "V40 Cross Country" to listOf("1.6 D Advance"),
        "V70" to listOf("2.4 D5 Premium", "2.5 T5"),
        "V90 Cross Country" to listOf("2.0 D D5 Pro"),
        "VW CC" to listOf("2.0 TDi 2.0 TDI", "1.4 TSi", "2.0 TDi Exclusive", "1.8 TFSi"),
        "Vectra" to listOf("1.6 GL", "1.6 Comfort", "1.6 Elegance", "1.8 Elegance", "1.9 CDTI Comfort", "1.6", "2.0 CD", "2.0 CDX", "2.0 GLS", "2.0 DTI Comfort", "1.8 CD", "1.9 CDTI Elegance", "1.8 Comfort", "1.6 Edition", "2.0", "1.6 Design Edition", "2.2 DTI Elegance", "1.6 Essentia", "2.2 Elegance", "2.0 100.Yıl", "2.5 CDX", "2.0 DTI CD", "2.2 DTI Comfort"),
        "Vega" to listOf("1.5", "1.6"),
        "Venga" to listOf("1.6 CRDi Panaroma Plus", "1.4 CRDi Active", "1.6 CRDi EX"),
        "Verso" to listOf("1.6 Elegant", "1.6 Comfort Extra", "1.6 D-4D Active", "1.6 Advance", "1.6 D-4D Premium Navi", "1.6 D-4D Elegant", "1.6 Premium", "1.6 D-4D Advance"),
        "Vista" to listOf("1.3 TDI Quadrojet Aura", "1.4 Safire Aura"),
        "Waja" to listOf("1.6 Base Line", "1.6 Medium Line", "1.6 Premium"),
        "X-Type" to listOf("2.0 D Executive", "2.1 Executive"),
        "XE" to listOf("2.0 D Prestige Plus", "2.0 D R-Sport Plus"),
        "XF" to listOf("2.2 D"),
        "Xantia" to listOf("2.0 SX"),
        "Xsara" to listOf("1.6 SX", "1.9 D", "1.4 HDi", "Picasso 1.6 HDi Exclusive", "1.4", "Picasso 1.6 SX"),
        "Yaris" to listOf("1.4 D-4D Fun", "1.3 Sol", "1.4 D-4D Sol", "1.33 Terra Sporty", "1.33 Fun", "1.33 Fun Special", "1.33 Cool Skypack", "1.3 Terra", "1.0 Terra Sporty", "1.0 Terra", "1.4 D-4D Terra", "1.33 Style Skypack", "1.4 D-4D Sol Special", "1.33 Cool", "1.33 Fun Special Skypack", "1.0", "1.33 Style", "1.0 Life", "1.0 Vision", "1.5 Dream", "1.33 Terra", "1.5 Hybrid Cool", "1.5 Dream Multidrive S", "1.5 Hybrid Spirit", "1.4 D-4D Executive", "1.3 Luna", "1.33 Sol", "1.5 Flame Multidrive S", "1.3 Sol Special", "1.33 Sport"),
        "Ypsilon" to listOf("1.3 Mjet"),
        "Zafira" to listOf("1.6 Comfort", "1.6 Elegance", "1.8 Elegance", "2.0 DTI Elegance", "1.6 Cosmo", "2.0 DTI Comfort", "1.8 Comfort", "1.6 GL", "1.9 CDTI Enjoy", "1.6 CDTI Enjoy"),
        "e-C4 X" to listOf("1.2 PureTech You"),
        "i10" to listOf("1.2 D-CVVT Elite", "1.0 D-CVVT Style", "1.0 D-CVVT Jump", "1.1 Select", "1.1 Team", "1.2 D-CVVT 25.Yıl Özel Seri", "1.2 MPI Elite", "1.0 MPI Jump"),
        "i20" to listOf("1.4 MPI Style", "1.2 MPI Jump", "1.4 MPI Jump", "1.4 CRDi Jump", "1.4 CRDi Style", "1.2 MPI Style", "1.2 D-CVVT Sense", "1.2 MPI Team", "1.4 CVVT Jump", "1.2 D-CVVT Jump", "1.4 MPI Style Plus", "1.4 MPI Elite Smart", "1.0 T-GDI Elite", "1.2 MPI Elite", "1.4 CRDi Team", "1.4 MPI Elite", "1.4 CVVT Sense", "1.0 T-GDI Style", "1.0 T-GDI Style Plus", "1.4 CVVT Team", "1.0 T-GDI Jump", "1.4 CRDi Elite", "1.0 T-GDI Star", "1.4 CVVT Select", "1.4 MPI Elite Plus", "1.4 CVVT Style", "1.2 D-CVVT Go", "1.4 CRDi Sense", "1.2 D-CVVT Elite", "1.4 CVVT Go", "1.4 MPI Star"),
        "i20 Active" to listOf("1.4 MPi Elite Smart", "1.4 MPi Elite"),
        "i20 N" to listOf("1.6 T-GDI"),
        "i20 Troy" to listOf("1.4 CRDi Mode", "1.4 CVVT Mode", "1.4 CRDi Team", "1.2 DOHC Mode", "1.2 DOHC Team", "1.4 CVVT Prime", "1.2 Start", "1.4 CRDi Start", "1.4 CVVT Team", "1.2 Team", "1.2 Mode", "1.4 CVVT Prime Plus"),
        "i30" to listOf("1.6 CRDi Team", "1.6 CRDi Prime", "1.6 CRDi CW Elite", "1.4 CVVT Team", "1.6 GDi Style", "1.6 CRDi Elite", "1.6 CRDi Mode", "1.6 GDi Elite", "1.6 CRDi Elite Plus Smart", "1.6 CRDi Style", "1.6 CRDi Select", "1.6 CVVT Select", "1.6 CVVT Mode", "1.6 CRDi Style Plus", "1.4 MPi Style", "1.6 CRDi Elite Plus", "1.6 CRDi Mode Plus"),
        "ix20" to listOf("1.4 CRDi Prime"),
        "Şahin" to listOf("S", "1.4"),
    )

    val vites_tipi=listOf("Düz","Otomatik","Yarı Otomatik")

    val renk = listOf(
        "Altın", "Bej", "Beyaz", "Bordo", "Diğer", "Füme", "Gri", "Gri (Gümüş)", "Gri (metalik)", "Gri (titanyum)", "Kahverengi", "Kırmızı",
        "Lacivert", "Mavi", "Mavi (metalik)", "Mor", "Pembe", "Sarı", "Siyah", "Turkuaz", "Turuncu", "Yeşil", "Yeşil (metalik)", "Şampanya"
    )

    val cekis=listOf("Önden Çekiş","Arkadan İtiş","4WD (Sürekli)","AWD (Elektronik)")

    val yil = (1975..2025).toList()

    val boyaDegisen=(0..15).toList()

    val yakit_tipi=listOf("Dizel","Benzin","LPG & Benzin","Hibrit","Elektrik")

    val kasa_tipi = listOf(
        "Cabrio", "Coupe", "Hatchback/3", "Hatchback/5", "MPV", "Pick-up", "Roadster", "SUV", "Sedan", "Station wagon"
    )









}